import '@/app/css/style.css'

import { Inter, Caveat } from 'next/font/google'
import localFont from 'next/font/local'
import Theme from '@/app/theme-provider'
import Header from '@/components/ui/header'
import QuoteTitle from '@/components/quote-title'
import Content from '@/components/ui/content'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const caveat = Caveat({
  subsets: ['latin'],
  variable: '--font-caveat',
  display: 'swap'
})

const orbiter = localFont({
  src: [
    {
      path: '../public/fonts/OrbiterDisplay-Bold.woff',
      weight: '700'
    }
  ],
  variable: '--font-orbiter',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  params: { quote }
}: {
  children: React.ReactNode
  params: { quote: string }
}) {
  return (
    <html className="dark" lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${caveat.variable} ${orbiter.variable} font-inter antialiased bg-white text-slate-800 dark:bg-slate-950 dark:text-slate-200 tracking-tight`}
      >
        {children}
      </body>
    </html>
  )
}
